name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' ? 'production' : 'development' }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_version: '1.1.0'

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -out=tfplan

    - name: Show Plan
      run: terraform show tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve tfplan

    - name: Save Terraform Plan as Artifact
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v2
      with:
        name: terraform-plan
        path: tfplan

